name: Databricks_so_file_Deployment
on:
  push:
    branches: sofilebranch
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: unzip artifact for deployment
      run: unzip velocity_modules.zip
      
    - uses: actions/checkout@v2
    - run: mkdir -p source/artifact
    - run: echo hello > source/kdp_databricks.cpython-38-x86_64-linux-gnu.so
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: source/kdp_databricks.cpython-38-x86_64-linux-gnu.so
        
    - name: Run Pre-deployment scripts
      shell: powershell
      run: mkdir "WebApp_Source"
      
    - name: Run Script
      shell: powershell
      run: |
        ./scripts/databricks.cicd.tools.ps1
