on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.KAGOOL_GITHUB_CREDENTIALS }}
        enable-AzPSSession: true
        
    - name: check out repo
      uses: actions/checkout@v2
    
    - name: Import Databricks notebooks    
      uses: microsoft/databricks-import-notebook@v1.0.0
      with:
        databricks-host: https://adb-2466824116276953.13.azuredatabricks.net
        databricks-token: dapic0ad793e62f534c98a44957f0708a304-2
        local-path: ./rajesh
        remote-path: /Folder1
