name: Databricks_so_file_Deployment
on:
  push:
    branches: sofilebranch
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: unzip artifact for deployment
      run: unzip velocity_modules.zip
