on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Download & Extract
      uses: gamedev-thingy/Download-Extract@done
     with:
        url:./source 
        destination:./source 
        ZIPname:./source/source
