name: upload-dbfs-file

on:
  push:
    branches: upload-dbfs
  workflow_dispatch:
  
env:
  DATABRICKS_HOST: https://adb-2466824116276953.13.azuredatabricks.net
  DATABRICKS_TOKEN: dapic0ad793e62f534c98a44957f0708a304-2
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repo
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KAGOOL_GITHUB_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Upload Wheel
        uses: databricks/upload-dbfs-temp@v0
        id: upload_so_file
        with:
          local-path: rajesh/kdp_functions.cpython-37m-x86_64-linux-gnu.so
