name: Upload_dbfs_file
on:
  push:
    branches:
      - upload-dbfs
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: rajesh
          path: rajesh/
